### ISSUE TITLE
Python 3.8.5 requirement.

### ISSUE THREAD

**Issue by alatteri** [talosh/flameTimewarpML#31]
Hello Talosh,

In your central install documentation, you list Python 3.8.5 as a requirement.  Even in the CentOS 8.2 the most recent version is 3.8.3.  Given that all flames are on CentOS 7.6 and won't be moving to CentOS 8.3 or newer in a very long time, this requirement is a bit hard to meet.   Would you be able to either provide some additional documentation on getting Python 3.8.5 installed in a "ADSK safe" way or get things working with a less stringent Python version requirement.

Thanks,
Alan

**Comment by talosh** [comment]
Hi Alan,
It should be fine even on CentOS 7.4 and tested on Centos7.6 with ADSK install.
The trick is to use separate isolated python environment with Miniconda3, and it does not interfere with the system python install.

This way it is perfectly ADKS - safe, as the whole Python 3.8 tree and libraries are in separate place and 
runs in isolated way only for the purpose to serve the Timewarp tools.

Hope that helps,
Andriy.
