### ISSUE TITLE
pip requirements failure.

### ISSUE THREAD

**Issue by alatteri** [talosh/flameTimewarpML#32]
```
[alan@ws104 flameTimewarpML]$ pip3 install -r requirements.txt 
Collecting numpy (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting tqdm (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/d9/13/f3f815bb73804a8af9cfbb6f084821c037109108885f46131045e8cf044e/tqdm-4.57.0-py2.py3-none-any.whl
Collecting torch (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/90/4f/acf48b3a18a8f9223c6616647f0a011a5713a985336088d7c76f3a211374/torch-1.7.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting opencv-python (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/bb/08/9dbc183a3ac6baa95fabf749ddb531bd26256edfff5b6c2195eca26258e9/opencv-python-4.5.1.48.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gvvshdzt/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gvvshdzt/opencv-python/

```

**Comment by talosh** [comment]
Are you sure it is done from Miniconda3 environment? There should be (base) before the command prompt and python --version should report 3.8.5
There is a small script to init environment in bundle folder - if you do init_env and provide your miniconda3 installation folder as an argument it should opent another console (or terminal on mac) and it should be (base) before command prompt

**Comment by alatteri** [comment]
> There should be (base) before the command prompt and python --version should report 3.8.5
I'm not sure what that means.  What is (base)?

Below is my full command syntax.  When I run init_env, there is no output.

```
[alan@ws104 timewarpML]$ mkdir -p /vol/pipeline/adsk/hooks/miniconda3
[alan@ws104 timewarpML]$ mkdir -p /vol/pipeline/adsk/hooks/flameTimewarpML
[alan@ws104 timewarpML]$ cp -a flameTimewarpML/bundle/* /vol/pipeline/adsk/hooks/flameTimewarpML
[alan@ws104 timewarpML]$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
[alan@ws104 timewarpML]$ sh Miniconda3-latest-Linux-x86_64.sh -bu -p /vol/pipeline/adsk/hooks/miniconda3
[alan@ws104 ~]$ /vol/pipeline/adsk/hooks/flameTimewarpML/init_env /vol/pipeline/adsk/hooks/miniconda3/
```

**Comment by alatteri** [comment]
Wait I think I see.  We need to run the pip from miniconda/bin ?

**Comment by talosh** [comment]
[alan@ws104 ~]$ /vol/pipeline/adsk/hooks/flameTimewarpML/init_env /vol/pipeline/adsk/hooks/miniconda3/

After this line it should open another terminal window, the propmpt there should look like: (base) [alan@ws104 ~]$

**Comment by alatteri** [comment]
> [alan@ws104 ~]$ /vol/pipeline/adsk/hooks/flameTimewarpML/init_env /vol/pipeline/adsk/hooks/miniconda3/
> 
> After this line it should open another terminal window, the propmpt there should look like: (base) [alan@ws104 ~]$

I see the problem.  I was doing this remotely via SSH terminal.  Doesn't pop up new window.

**Comment by alatteri** [comment]
Maybe a better way to document this, is to run pip from within miniconda/bin

**Comment by talosh** [comment]
in init_env at the very end you can change the line: 
cmd_prefix = 'konsole -e /bin/bash --rcfile ' + tmp_bash_rc_file
to:
cmd_prefix = '/bin/bash --rcfile ' + tmp_bash_rc_file

I think it will do it over ssh
