### ISSUE TITLE
tons of failure errors in flame on startup. 

### ISSUE THREAD

**Issue by alatteri** [talosh/flameTimewarpML#33]
See attached logs.
[flame20212_ws104_app.log](https://github.com/talosh/flameTimewarpML/files/6024884/flame20212_ws104_app.log)
[flame20212_ws104_shell.log](https://github.com/talosh/flameTimewarpML/files/6024885/flame20212_ws104_shell.log)

**Comment by talosh** [comment]
this guys - both miniconda3 and bundle folders - should not live under flame hooks folder. It is trying now to start every single python file from there diving into subfolders. It should be safe to move it one or two levels up to avoid it. ie:
mv /vol/pipeline/adsk/hooks/miniconda3 /vol/pipeline/adsk/

**Comment by talosh** [comment]
the only file to be placed in hooks folder is flameTimewarpML.py

**Comment by alatteri** [comment]
Got it.  I had to place those folder two up, into just /vol/pipeline.  Thanks for the help!!
