### ISSUE TITLE
Environment variable for tmp location

### ISSUE THREAD

**Issue by alatteri** [talosh/flameTimewarpML#34]
Our machines have no local frame store.  Only a boot disk for OS& Apps.   

This means the default /var/tmp location is not desirable.  Counting on our artists to switch to a proper temp location is not reliable.  Can you add an environment variable that would at least default to the location of choice.

Thanks,
Alan

**Comment by talosh** [comment]
This will something to be implemented in the next wersion.
In the meantime it can be done by editing flameTimewarpML.py file.
After line 1039 in flameTimewarpML.py add:
self.working_folder = os.getenv(‘FLAMETWML_WORK_FOLDER’)
This will set working folder to env variable FLAMETWML_WORK_FOLDER.
The path can be set directly as well.

Then search for the lines that says:
vbox.addLayout(hbox_workfolder)
and comment these lines out. This will remove the folder selectors from the dialog boxes.

**Comment by talosh** [comment]
Pleae leave this issue open until it is properly implemented in the next release

**Comment by talosh** [comment]
implemented in v0.4.1
