### ISSUE TITLE
Installed but no processing.

### ISSUE THREAD

**Issue by alatteri** [talosh/flameTimewarpML#35]
Hi again.

I seem to have everything centrally installed properly now, no processing seems to be happening.  It exports the shots, then nothing.

```
[flameTimewarpML] creating folders: /var/tmp/CF5000_NR01-RSZ_Result_TWML4_2021FEB22_1340_8AA/source
[flameTimewarpML] Executing command: echo "/var/tmp/CF5000_NR01-RSZ_Result_TWML4_2021FEB22_1340_8AA">/vol/pipeline/flameTimewarpML/locks/83B1920FC647E560A256A0F031BD225510AA3C78.lock
[flameTimewarpML] Executing command: konsole -e /bin/bash -c 'eval "$(/vol/pipeline/miniconda/bin/conda shell.bash hook)"; conda activate; cd /vol/pipeline/flameTimewarpML/; echo "Received 1 clip to process, press Ctrl+C to cancel"; trap exit SIGINT SIGTERM; python3 /vol/pipeline/flameTimewarpML/inference_sequence.py --input /var/tmp/CF5000_NR01-RSZ_Result_TWML4_2021FEB22_1340_8AA/source --output /var/tmp/CF5000_NR01-RSZ_Result_TWML4_2021FEB22_1340_8AA --model /vol/pipeline/flameTimewarpML/trained_models/default/v2.0.model --exp=2; '

```

**Comment by alatteri** [comment]
If I run the full command string from the last line, I got the following errors in shell

```
[alan@ws104 ~]$ X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 20 (X_GetProperty)
  Resource id:  0x19800154
```

**Comment by talosh** [comment]
This doesn't look right. 
If you just do 'konsole -e /bin/bash' does it open new window with shell?
And if you press Ctrl and click continue in dialog in Flame, does it open konsole window and say something there?

**Comment by alatteri** [comment]
Yes, that will open a shell, and the error does come up only when I close it.
I noticed that when trying flametimeml, a shell does pop up and immediately goes away.  I also tried setting DEBUG = True, but no new relevant info is printed.

**Comment by alatteri** [comment]
I think I figured it out.  Type in environment variable.  Will confirm and close issue.

**Comment by talosh** [comment]
If you hold Ctrl while clicking 'Continue" in Flame in TW dialog box the window should stay open

**Comment by talosh** [comment]
It won't close it automatically so one can see what errors are there

**Comment by alatteri** [comment]
While I did have a typo, that did not fix the issue.  This is the output from holding CTL.   Nor sure where it is still getting the 'adsk' path from.   Miniconda is /vol/pipeline root.

/bin/bash: /vol/pipeline/miniconda3/bin/conda: /vol/pipeline/adsk/miniconda3/bin/python: bad interpreter: No such file or directory
```
/bin/bash: conda: command not found
Received 1 clip to process, press Ctrl+C to cancel
Traceback (most recent call last):
  File "/vol/pipeline/flameTimewarpML/inference_sequence.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Commands finished. You can close this window

```

**Comment by talosh** [comment]
It might just stuck somewhere in env variables related to Miniconda.
Maybe give it a reboot and then If you just do init_env script and specify /vol/pipeline/miniconda3 to check if it works?
Another option would be to remove /vol/pipeline/miniconda3 and reinstall it, and then do pip3 again.

**Comment by talosh** [comment]
It looks like you'll have to reinstall it to the right directory:
https://docs.anaconda.com/anaconda/user-guide/tasks/move-directory/
It says: If you simply copy the Anaconda files to a new directory, Anaconda will not work.
That's probably the case here

**Comment by alatteri** [comment]
That did it.  I re-installed miniconda from scratch.  Thanks for the help.

**Comment by talosh** [comment]
My bad, I tought one can just move it but it's not the case. 
Thank you for the amazing trial, I'll put all the stumbling block to docs
