### ISSUE TITLE
Option to delete shot work folder

### ISSUE THREAD

**Issue by alatteri** [talosh/flameTimewarpML#48]
It would be great if there was an option to delete the shot work folder when done.  And an environment variable controlling its default state.  Personally I see no need to keep that stuff around after the result has been imported into the flame.

**Comment by talosh** [comment]
The thing is I can not see an option to hard-import media into Flame with python. Currently the workaround for the script is to open the imported clip as a sequence, drop a bogus timeline effect on it, render it so it gets itself to framestore and execute shortcut to hard-commit. The code that does it is already there and can be easily enabled, I'll do a switch with env variable for that

**Comment by alatteri** [comment]
I forgot about that aspect.  I also asked Andy Milikia to look into the flame python and see if there is a Cache option.

**Comment by amilkis** [comment]
Hello! Here's what I can tell you:  I don’t see anything in the python API to cache media on import, but  you can cache the current/selected clip with the command cache_media. So it’s possible that after he imports the clip back in the clip can then be cached.

**Comment by talosh** [comment]
this is implemented in v0.4.2, could you guys please check if it works for you?

**Comment by alatteri** [comment]
This works great!!!  Thanks.  closing issue.
