### ISSUE TITLE
Support for RTX 30 series

### ISSUE THREAD

**Issue by halalmeats** [talosh/flameTimewarpML#5]
The bundle works really well on my old 2080 but when I switch to my 3080 I run into cuda errors. 

Is it possible to compile this to work with the newer cards?

Thanks!

**Comment by talosh** [comment]
Hi, if you launch nvidia-smi what coda version it says your driver is linked to?
I think it one could try to install different pytorch builds and nvidia drivers but I don’t have any access to the machine with 3080 at the moment.
Let me know your coda version and let’s try a couple of options.

**Comment by halalmeats** [comment]
Hey there,

I'm running cuda version 11.2 and driver 460.32.03 (if relevant)

That would be awesome! Thanks

**Comment by talosh** [comment]
The core library here calls pytorch and their website is https://pytorch.org. There's only 11.0 currently mentioned currently, so you could probably try: pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html as suggeted. Make sure you're running it from within miniconda3 environment it should be activated before with init_env script. There are some cutting-edge nightly unstable builds as well, maybe worth to try if the one above did not help: pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html

**Comment by halalmeats** [comment]
That worked a treat, thanks! Just using the stable torch builds was enough. RAD!

**Comment by talosh** [comment]
Pleased to hear that! 
Could you please try to use this version as well: https://github.com/talosh/flameTimewarpML/releases/tag/v0.2.0.beta.018
It has major speed improvements (literally 10x faster) with removing congestion in output queue. This should allow you to really use 3080 speed. Miniconda3 is backed up on bundle unpack so it should be fine just to replace the newly installed one with the one backed up to get cuda11 back

**Comment by halalmeats** [comment]
Just gave it a test. It is definitely faster! (Previous version was averaging ~2.5fps on the 52000x1200 image sequence im working on. New version is more like 5fps) 

However, I'm receiving this error when timewarping a large file sequence. it always drops out on the same frame number. Write buffer fule?

[https://i.imgur.com/OxScoww.png](url)

**Comment by talosh** [comment]
I will have to look into it it when I have time it comes from Linux and has to do with files limit. Could you try to check yours and increase it as discribed here: https://www.tecmint.com/increase-set-open-file-limits-in-linux/

**Comment by talosh** [comment]
this looks like a bug in open-cv library: https://github.com/opencv/opencv/issues/12342
So the workaround at the moment is to increase max number of open files for OS

**Comment by halalmeats** [comment]
Setting the user level limits in /etc/security/limits.conf worked! I didn't bother testing whether it was the soft or hard setting (or both) which fixed the issue.

The sysctl method doesn't work for this issue.

Thanks!
