### ISSUE TITLE
Central install still requires flameTimewarpML/locks to be world writeable

### ISSUE THREAD

**Issue by alanmcseveney** [talosh/flameTimewarpML#79]
Is there an alternative to flameTimewarpML/locks being world writeable?  We have our deployments centralized, and non-admins should not be able to, or have to, write into the central repository.

**Comment by daveoy** [comment]
https://github.com/talosh/flameTimewarpML/pull/82 should fix that @alanmcseveney  @talosh

**Comment by talosh** [comment]
Hi guys, I’d like to give you an access to the repository in order for you to be able to improve current v0.4 branch.
I’m quite focused on v0.5 now and don’t have much time at the moment to look through pull requests.
If you happen to know someone else from Flame community who would like to have it please let me know
