### ISSUE TITLE
python quit unexpected

### ISSUE THREAD

**Issue by Tam-Gift** [talosh/flameTimewarpML#97]
Hi install latest TimewarpML, install all ok. But when i create fluidmorph transition it show python quit and i go to privacy and security on mac it said : "python" was blocked from use because it is not from an identified developer, i also open anyway with password but it not solve. Can i ask how can i fix this.
P/s: My mac is m2 ultra, Sonama 14.5. Flame 2024. tks

**Comment by talosh** [comment]
It is a standard MacOS quarantine attribute, please use bundled fix-xattr.command to clear it
